### ISSUE TITLE
H3Index differs between .Net version and JS version.

### ISSUE THREAD

**Issue by git1** [RichardVasquez/h3netOld#2]
I was testing H3.Net and wanted to cross check it against Javascript version of the api at 3.2.0. I realized that the H3Index generated by .Net version and JS version differs even though they both are returned as valid index. 

.Net code
 GeoCoord gc = new GeoCoord(27.700769, 85.300140);
            var index = Api.GeoToH3(gc, 7);
            Console.WriteLine(index);
            Console.WriteLine(Api.H3IsValid(index));

Result: 
873F512E5FFFFFF
1

JavaScript code: (npm install h3-js@3.2.0)
const h3 = require("h3-js");
const h3Index = h3.geoToH3(27.700769, 85.300140, 7);
console.log(h3Index);
console.log(h3.h3IsValid(h3Index));

Result:
873c02992ffffff
true

Note: JS will produce same index for newer version of H3.

**Comment by RichardVasquez** [comment]
I'll be happy to review a PR.  H3net _currently_ is low priority for me due to real life circumstances.  I hope to change that sometime around the middle of next year, but it is what it is.

**Comment by isaacbrodsky** [comment]
I did a little testing and I think this is because the .Net API expects radians instead of degrees.

This test passed:
```
            GeoCoord gc = new GeoCoord();
            GeoCoord.setGeoDegs(ref gc, 27.700769, 85.300140);
            Assert.AreEqual(Api.GeoToH3(gc, 7), 0x873c02992ffffffL);
```

The Uber bindings convert from degrees to radians for you. This doesn't because it's a translation of the core library.

**Comment by RichardVasquez** [comment]
> I did a little testing and I think this is because the .Net API expects radians instead of degrees.
> 
> This test passed:
> 
> ```
>             GeoCoord gc = new GeoCoord();
>             GeoCoord.setGeoDegs(ref gc, 27.700769, 85.300140);
>             Assert.AreEqual(Api.GeoToH3(gc, 7), 0x873c02992ffffffL);
> ```
> 
> The Uber bindings convert from degrees to radians for you. This doesn't because it's a translation of the core library.

Thanks, @isaacbrodsky .  I'd had a shower thought on that earlier this morning, and was going to take a look at it this evening.  Closing.
